# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc396b74fdfc9bedd24ee6ada51d67139c07e292ba8626e4052f2387c8beb64409034ee6238bf6f5e216fef8388793ccb58d29c55cf90ddcf49985eaf8a878af

test:
  secret_key_base: 38dbdc2ebc6966b124499c59aef0765bdf7d1235cf4ad15cb6f839b1dcd04cfe2d042591a8b974f3da05882d071f1d9db7421a11b88d88b603539bb4f804b1b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
